services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: connectchat
      POSTGRES_PASSWORD: connectchat
      POSTGRES_DB: connectchat
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  postgres_test:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: connectchat
      POSTGRES_PASSWORD: connectchat
      POSTGRES_DB: connectchat_test
    ports:
      - "5433:5432"

volumes:
  pgdata:
